### PR TITLE
add : dummy a.a.a to make the new pl compile

### PR DESCRIPTION
**Pull request by AlucardTN**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
The new what? Also, these files were anonymous classes that got obfuscated outside their package name. Please decompile these files, and put them as anonymous classes in the decompiled class that references them.

**Comment by MarkDroid** [comment]
add those because yeb, they are some a.a.a fields generated to make some classes in com.besome.sketch.beans and editor compile !!!

**Comment by Iyxan23** [comment]
hi bor

**Comment by DantaNotEpic** [comment]
real conversation here, adios

**Comment by MarkDroid** [comment]
i cant decmpile all those a.a.a classes man!, just they are a o onclick listener, and which they are not even needed

**Comment by JavkhlanK** [comment]
mmm alright I'll add them now, but then decompile and bring their functionality back to the original uses later

**Comment by MarkDroid** [comment]
yes, okay, this may take many time

**Comment by AlucardTN** [comment]
merge !!!

**Pull request merged**
