### PR TITLE
Create SketchDialog.java

### PR DESCRIPTION
**Pull request by hasrat-ali**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Any use of it until now? Also, having public fields and setters, but no getters isn't good. Can you either make (most) fields private and add necessary getters or remove the setters?

**Comment by hasrat-ali** [comment]
So far there is no use, but it has been used in VersionDialog.

**Comment by JavkhlanK** [comment]
now some getters are missing, like `getDialogImage()`

**Comment by hasrat-ali** [comment]
What is the use of getDialogImage().

**Comment by JavkhlanK** [comment]
It should return `dialog_img`, and also be public.

**Comment by hasrat-ali** [comment]
I have updated but I do not think it is necessary.

**Comment by JavkhlanK** [comment]
Those getters would be great for all private Views in that class.

**Pull request closed without merging**
