### PR TITLE
Add Pro Badges

### PR DESCRIPTION
**Pull request by DantaNotEpic**
Por Badges For Por People 😎😎😎

### CODE REVIEW

**Comment by JavkhlanK** [comment]
mmm epic swaggers pogchamp us por modirs 😎😎😎😎

**Comment by DantaNotEpic** [comment]
poger 😎😎😎😎😎

**Comment by DantaNotEpic** [comment]
😔

**Comment by MarkDroid** [comment]
elo dentaepik !! hi bor ??>??

**Comment by DantaNotEpic** [comment]
halo bor

**Comment by DantaNotEpic** [comment]
me just waiting to be merged :pensive:

**Comment by JavkhlanK** [comment]
apensivefast

**Comment by DantaNotEpic** [comment]
discord emote in github!!?!?!?!?! how

**Comment by MarkDroid** [comment]
hakir?????@?@@?!?!!

**Comment by Iyxan23** [comment]
<p>ez bor </p>

**Comment by DantaNotEpic** [comment]
you hakir too!?!?!??!?!?!!!&~ 😔😔😔

**Comment by JavkhlanK** [comment]
omg por hakir hir tu....!! welcam to geng

**Comment by DantaNotEpic** [comment]
merge the pull or damb!!!

**Comment by DantaNotEpic** [comment]
Jbk0 Is Damb Confirmed 😎

**Comment by ilyassesalama** [comment]
Can you close this pull request?

**Comment by DantaNotEpic** [comment]
nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by DantaNotEpic** [comment]
😔😔😔😔😔

**Comment by AlucardTN** [comment]
nub 😎

**Pull request closed without merging**
