### PR TITLE
Update JavaSyntaxManager.java

### PR DESCRIPTION
**Pull request by hosni-fraj**
`PATTERN_COMMENT`
Not work in android 8--
So, I removed it by make its label blank

### CODE REVIEW

**Comment by hasrat-ali** [comment]
You need to define correct Regular Expression Pattern.

**Comment by JavkhlanK** [comment]
This seems to break highlighting comments. Please fix the regular expression, instead of removing/breaking it.

**Comment by JavkhlanK** [comment]
Already fixed now.

**Comment by hosni-fraj** [comment]
**OK **

**Pull request closed without merging**
