### PR TITLE
Updated MenuBean.java

### PR DESCRIPTION
**Pull request by hasrat-ali**
Added Values from value/values.xml

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Looks good! I'm sorry, but I misremembered, the files in this repository have 2 spaces as independents. Could you please fix them again? 😅

**Comment by DantaNotEpic** [comment]
_**B E A N**_

**Comment by hasrat-ali** [comment]
Which files?

**Comment by JavkhlanK** [comment]
Only this file, for now. All upcoming files should use 2 spaces though.

**Pull request merged**
