### PR TITLE
docs: source code map and disclaimer

### PR DESCRIPTION
**Pull request by ilyassesalama**

### CODE REVIEW

**Comment by Iyxan23** [comment]
<span>shouldn't this be `docs:`? </span>

**Comment by hasrat-ali** [comment]
Much better now.

**Comment by ilyassesalama** [comment]
> shouldn't this be `docs:`? 


meh, i think it's better to keep everything simple and clean in 1 page

**Comment by Iyxan23** [comment]
<span>no, the commit message should be prefixed with `docs:` as you've modified the documentation (README.md in this case) </span>

**Comment by ilyassesalama** [comment]
ok i'm changing it

**Comment by JavkhlanK** [comment]
kinda reminds me of `_Mod_README.txt` inside the APKs, looks good

**Comment by DantaNotEpic** [comment]
bor, many haxker 😔

**Comment by JavkhlanK** [comment]
says notahakhir

**Comment by DantaNotEpic** [comment]
😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔

**Pull request merged**
